"""empty message

Revision ID: 050f0059c57b
Revises: 
Create Date: 2020-11-07 16:02:06.980836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050f0059c57b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osoba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osoba_username'), 'osoba', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_osoba_username'), table_name='osoba')
    op.drop_table('osoba')
    # ### end Alembic commands ###
