"""empty message

Revision ID: 1d3e9b057e3d
Revises: d759fe8132f4
Create Date: 2020-11-11 15:27:22.642635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3e9b057e3d'
down_revision = 'd759fe8132f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('numerPaczki',
    sa.Column('numerPaczki', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('numerPaczki')
    )
    op.create_table('numerZamowienia',
    sa.Column('numerZamowienia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('numerZamowienia')
    )
    op.drop_constraint('osoba_password_key', 'osoba', type_='unique')
    op.create_unique_constraint(None, 'osoba', ['nrTelefonu'])
    op.create_unique_constraint(None, 'osoba', ['PESEL'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'osoba', type_='unique')
    op.drop_constraint(None, 'osoba', type_='unique')
    op.create_unique_constraint('osoba_password_key', 'osoba', ['password'])
    op.drop_table('numerZamowienia')
    op.drop_table('numerPaczki')
    # ### end Alembic commands ###
