"""empty message

Revision ID: 1ecc3bbb4cd5
Revises: 
Create Date: 2020-11-07 17:15:04.295961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecc3bbb4cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osoba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eMail', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('imie', sa.String(length=100), nullable=True),
    sa.Column('nazwisko', sa.String(length=100), nullable=True),
    sa.Column('nrTelefonu', sa.String(length=12), nullable=True),
    sa.Column('PESEL', sa.String(length=11), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password')
    )
    op.create_index(op.f('ix_osoba_eMail'), 'osoba', ['eMail'], unique=True)
    op.create_table('klient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adres', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['osoba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kurier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aktualnePolozenie', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['osoba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kurier')
    op.drop_table('klient')
    op.drop_index(op.f('ix_osoba_eMail'), table_name='osoba')
    op.drop_table('osoba')
    # ### end Alembic commands ###
